config/routes.rb
Sheriff::Application.routes.draw do
  match '/', :to => redirect('/alerts')

  resources :alerts do
    collection do
      delete :delete_all
    end
  end
  resources :groups
  resources :reports do
    collection do
      post :batch_validate
      post :clear_alerts
    end
  end
  resources :validations
  resources :deputies do
    collection do
      post :batch
    end
  end
  resources :plugins
  resources :settings do
    collection do
      post :update
      get  :test
      post :reset
    end
  end

  match "/notify", :to => "reports#create"
  match "/resque" => ResqueWeb, :anchor => false if CFG[:resque]
  match '/health', :to => "alerts#health"
end

app/models/deputy.rb
class Deputy < ActiveRecord::Base
  include ErrorLevelPropagation

  # inline schema
  col "name",                :null => false
  col "address",             :null => false
  col "last_report_at",      :type => :datetime
  col "current_error_level", :type => :integer, :default => 0, :null => false
  col "human_name"
  col "disabled_until",      :type => :datetime
  col "deleted_at",          :type => :datetime
  col_timestamps

  add_index [:address], :unique => true


  has_many :reports, :dependent => :destroy
  has_many :deputy_plugins, :dependent => :destroy
  accepts_nested_attributes_for :deputy_plugins

  validates_uniqueness_of :address
  validates_uniqueness_of :name, :if => lambda{|d| d.name != UNKNOWN_HOST }
  validates_uniqueness_of :human_name, :allow_blank => true

  UNKNOWN_HOST = 'unknown_host'
  UNKNOWN_ADDRESS = 'unknown_address'

  def self.visible
    self.where(:deleted_at => nil)
  end

  def full_name
    "#{human_name.presence || name}"
  end

  def update_last_report_at!
    return if last_report_at and last_report_at > 1.minute.ago
    update_attributes(:last_report_at => Time.current)
  end

  def update_name!(name)
    return if name.blank?
    update_attributes(:name => name) if self.name != name
  end

  def disabled?
    disabled_until? and disabled_until > Time.current
  end

  def self.find_by_address_or_name(address, name)
    if name == UNKNOWN_HOST and address == UNKNOWN_ADDRESS
      raise 'Cannot possibly find anything'
    elsif name == UNKNOWN_HOST
      first(:conditions => {:address => address})
    elsif address == UNKNOWN_ADDRESS
      first(:conditions => {:name => name})
    else
      first(:conditions => ["name = ? OR address = ?", name, address])
    end
  end

  def self.find_or_create_by_address_or_name(address, name)
    find_by_address_or_name(address, name) || create!(:address => address, :name => name)
  end

  def self.extract_address_and_name(request)
    [extract_ip(request), extract_host(request)]
  end

  def self.extract_host(request)
    request.params[:hostname].presence || request.remote_host.presence || UNKNOWN_HOST
  end

  def self.extract_ip(request)
    request.params[:ip].presence ||
      (request.params[:forced_host] ? UNKNOWN_ADDRESS : request.ip)
  end

  def self.move_settings_from_to(old_ip, new_ip)
    old_deputy = Deputy.find_by_address(old_ip)
    new_deputy = Deputy.find_by_address(new_ip)

    ### reports
    reports = old_deputy.reports
    reports.map{|r| r.update_attributes(:deputy_id => new_deputy.id)}

    ### plugins
    plugins = old_deputy.deputy_plugins
    plugins.map{|r| r.update_attributes(:deputy_id => new_deputy.id)}
  end

  def delete
    # set deleted_at for self
    self.update_attributes(:deleted_at => Time.current)
    self.deputy_plugins.map(&:delete)
    self.reports.map(&:delete)
  end
end

app/controllers/deputies_controller.rb
class DeputiesController < RestController
  before_filter :convert_plugin_interval, :only => [:update, :create]

  def batch
    deputies = my_actions.create_plugins_for_deputies
    redirect_to :back, :notice => "Added #{deputies.size} plugins!"
  end

private
  def collection
    default_oder = ActiveRecord::Base.connection.class.concat_sql("COALESCE(human_name,'')", "name")
    params[:order] ||= default_oder
    scope = resource_class.visible
    @collection    ||= scope.page(params[:page]).per(params[:per_page].presence || 40).order(params[:order])
  end

  def my_actions
    @my_actions ||= DeputyActions.new(params)
  end

  # just delegate to actions class
  def convert_plugin_interval
    my_actions.convert_plugin_interval
  end
end

app/views/deputies/edit.erb
<% if @deputy.current_error_level != 0 %>
  <%= form_for @deputy do |f| %>
    <%= f.hidden_field :id %>
    <%= f.hidden_field :current_error_level, {:value => 0} %>
    <%= submit_tag 'reset error level', :class => 'btn btn-primary' %>
    <a rel="popover"
            title="Reset Error Level"
            data-content='sometimes error level needs manual resetting'>
          <i class='icon-question-sign'></i>
    </a>
  <% end %>
<% end %>


<%= form_for @deputy do |f| %>
  <%= f.error_messages %>

  <table class="sharp">
    <tr>
      <td>Human Name</td>
      <td><%= f.text_field :human_name %></td>
    </tr>
    <tr>
      <td>Name (Used for recognition!)</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>Address (Used for recognition!)</td>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
      <td>Disabled until</td>
      <td><%= f.text_field :disabled_until, :value => @deputy.disabled_until.try(:to_s, :db) %></td>
    </tr>
  </table>

  <% @deputy.deputy_plugins.build %>
  <h3>Plugins</h3>
  <div class="well">
    <% if Plugin.any? %>
      <%= f.fields_for :deputy_plugins do |child| %>
        <%= child.hidden_field :deputy_id %>
        <%= child.select :plugin_name, [nil] + Plugin.names %>
        every
        <%= child.text_field :interval_value, :size => 5, :class => 'span1'  %>
        <%= child.select :interval_unit, time_units_for_select(:without => 'Seconds'), {}, :class => 'span2' %>
        <br />
      <% end %>
      <%= submit_tag 'Save', :class => 'btn btn-primary' %>
    <% else %>
      <%= link_to 'Create your first plugin now :)', new_plugin_path %>
    <% end %>
  </div>
<% end %>

<h3>Reports <small>(Last report <%= time_ago @deputy.last_report_at %>)</small></h3>
<table class="sharp">
  <tr>
    <th></th>
    <th><%= sort_head 'Group', :column => :group_id %></th>
    <th><%= sort_head 'Value' %></th>
    <th><%= sort_head 'Reported at' %></th>
    <th></th>
  </tr>
  <% @deputy.reports.all(:include => [{:group => :group}, :validations], :order => (params[:order] || 'reported_at desc'), :limit => 30).each do |report| %>
    <%= render :partial => 'reports/report_row', :locals => {:report => report, :hide_deputy => true} %>
  <% end %>
</table>

app/views/deputies/index.erb
<%= paginate collection %>

<%= form_tag '/deputies/batch' do %>
  <table width="100%" class="sharp">
    <tr style="font-weight:bold;">
      <td></td>
      <td><%= sort_head 'Name' %></td>
      <td><%= sort_head 'IP', :column => :address %></td>
      <td><%= sort_head 'Last Report', :column => :last_report_at %></td>
      <td></td>
    </tr>
    <% collection.each do |deputy| %>
      <tr <%= error_attribute(deputy) %>>
        <td><%= check_box_tag 'ids[]', deputy.id, false, :class => 'deputy_id' %></td>
        <td><%= link_to_object deputy %></td>
        <td><%= deputy.address %></td>
        <td><%= time_ago deputy.last_report_at %></td>
        <td><%= button_to_delete deputy, :text => 'x' %></td>
      </tr>
    <% end %>
  </table>

  <%= toogle_all_check_boxes 'deputy_id', {:class => 'btn'} %>

  Run <%= select_options_tag 'deputy_plugin[plugin_name]', [nil] + Plugin.names %>
  every
  <%= text_field_tag 'deputy_plugin[interval_value]', '', :size => 5, :class => 'span1' %>
  <%= select_options_tag 'deputy_plugin[interval_unit]', time_units_for_select(:without => 'Seconds'), {:class => 'span1'} %>
  <%= check_box_with_label 'overwrite', true, false, 'overwrite', {:class => 'checkbox inline'} %>
  <%= submit_tag 'update', :class => 'btn btn-primary' %>
<% end %>

<%= paginate collection %>