config/routes.rb
Sheriff::Application.routes.draw do
  match '/', :to => redirect('/alerts')

  resources :alerts do
    collection do
      delete :delete_all
    end
  end
  resources :groups
  resources :reports do
    collection do
      post :batch_validate
      post :clear_alerts
    end
  end
  resources :validations
  resources :deputies do
    collection do
      post :batch
    end
  end
  resources :plugins
  resources :settings do
    collection do
      post :update
      get  :test
      post :reset
    end
  end

  match "/notify", :to => "reports#create"
  match "/resque" => ResqueWeb, :anchor => false if CFG[:resque]
  match '/health', :to => "alerts#health"
end

app/models/alert.rb
class Alert < ActiveRecord::Base

  # inline schema
  col :error_level,     :type => :integer, :null => false
  col :message,         :type => :string,  :null => false
  col :validation_id,   :type => :integer, :null => false
  col :validation_type, :type => :string,  :null => false
  col :report_id,       :type => :integer, :null => false
  col :created_at,      :type => :datetime
  col :updated_at,      :type => :datetime


  belongs_to :validation, :polymorphic => true
  belongs_to :report
  # after_create :send_notification
  # after_create :report_to_fyrehose
  before_create :adjust_validation_type

  protected

  def adjust_validation_type
    self.validation_type = validation.class.to_s
  end

  def report_to_fyrehose
    ReporterFyrehose.send_alert(self)
  end

  def self.generate_alert_report(timeframe=nil)
    timeframe ||= 30.minutes
    alerts = Alert.find(:all,
        :conditions => ["created_at >= ? AND error_level > 1", Time.now.utc - timeframe ])
    Reporter.multi_notification(alerts, timeframe)
    if (sms_alerts = alerts.select{|x| x.error_level == 3}).size > 0
      sms_alerts.map{ |sms_alert| Reporter.send_sms(sms_alert) }
    end
  end
end

app/controllers/alerts_controller.rb
class AlertsController < RestController
  hacky_respond_to :html, :xml, :json

  def health
    render :text => 'OK'
  end

  def delete_all
    Alert.delete_all
    redirect_to :action => :index
  end

  def collection
    @collection ||= begin
      r = resource_class.page(params[:page]).per(20).
        order(params[:order] || 'id desc').
        includes(:report => [{:group => :group}, :deputy])
      r = r.group(:report_id) if params[:unique]
      r
    end
  end
end

app/views/alerts/index.erb
<%= paginate collection %>
<%= link_to 'delete all', delete_all_alerts_path, :method => :delete %>
<% if params[:unique] %>
  | <%= link_to 'non-unique', params.merge(:unique => nil) %>
<% else %>
  | <%= link_to 'unique', params.merge(:unique => 1) %>
<% end %>

<table class="sharp">
  <tr>
    <td><%= sort_head 'Reported at', :column => :id %></td>
    <td><%= sort_head 'Report', :column => :report_id %></td>
    <td><%= sort_head 'Message' %></td>
    <td><%= sort_head 'Lvl', :column => :error_level %></td>
    <td></td>
  </tr>
  <% collection.each do |alert| %>
    <tr <%= error_attribute(alert) %>>
      <td><%= detailed_time alert.created_at %></td>
      <td><%= link_to_object alert.report %></td>
      <td class='max_width_200'><%= visual_error(alert, alert.message) %></td>
      <td align=center><%= visual_error(alert) %></td>
      <td><%= button_to_delete alert, :text => 'x' %></td>
    </tr>
  <% end %>
</table>
<%= paginate collection %>